-- CreateKeycloakUser

CREATE USER "KEYCLOAK" IDENTIFIED BY "root";

-- Standard schema owner grants
GRANT CREATE TYPE TO "KEYCLOAK";
GRANT CREATE TRIGGER TO "KEYCLOAK";
GRANT CREATE PROCEDURE TO "KEYCLOAK";
GRANT CREATE VIEW TO "KEYCLOAK";
GRANT CREATE SESSION TO "KEYCLOAK";
GRANT CREATE INDEXTYPE TO "KEYCLOAK";
GRANT CREATE SEQUENCE TO "KEYCLOAK";
GRANT CREATE PUBLIC SYNONYM TO "KEYCLOAK";
GRANT CREATE JOB TO "KEYCLOAK";
GRANT CREATE MATERIALIZED VIEW TO "KEYCLOAK";
GRANT CREATE SYNONYM TO "KEYCLOAK";
GRANT CREATE TABLE TO "KEYCLOAK";

-- Required by Keycloak's Liquibase
GRANT SELECT ON SYS.DBA_RECYCLEBIN TO "KEYCLOAK";

ALTER USER "KEYCLOAK" quota unlimited on USERS;
